version: "3.8"

services:
  whoami:
    image: traefik/whoami
    networks:
      - web
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.swarm.localhost`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.docker.network=web"

networks:
  web:
    external: true
